### Get all users
GET https://cse341-project1-poea.onrender.com/contacts HTTP/1.1

### Get user by Id
GET https://cse341-project1-poea.onrender.com/contacts/69f99a38c65e6969e87fdab HTTP/1.1

### Create Contact
POST https://cse341-project1-poea.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Carl",
    "lastName": "Johansen",
    "email": "carl@email.com",
    "favColor": "Orange",
    "birthday": "March, 21, 1981"
}

### Update contact
PUT https://cse341-project1-poea.onrender.com/contacts/69f99a38c65e6969e87fdab5 HTTP/1.1
content-type: application/json

{
    "firstName": "Bjorn",
    "lastName": "Larsen",
    "email": "bjorn@email.com",
    "favColor": "Lime",
    "birthday": "January, 2, 1967"
}

### Delete contact
DELETE https://cse341-project1-poea.onrender.com/contacts/6a034c922fdc255edad3c26d HTTP/1.1